version: '3'
services:
  app:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "32769:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: